application:
  log:
    level: "%env(TWITCHBOT_LOG_LEVEL)%"
  providers:
    # - My\TwitchBot\Provider

bot:
  nickname: choccyb0t
  token: "%env(TWITCHBOT_BOT_TOKEN)%"
  channels:
    - martinph01
    - choccyb0t

broadcaster:
  token: "%env(TWITCHBOT_BROADCASTER_TOKEN)%"

events:
  listeners:
    # Choccybiccy\TwitchBot\Event\MessageEvent
    #  - My\TwitchBot\Event\Listener
