application:
  env: "%env(TWITCHBOT_ENV)%"
  log:
    level: "%env(TWITCHBOT_LOG_LEVEL)%"
  providers:
    # - My\TwitchBot\Provider

twitch:
  url: "wss://irc-ws.chat.twitch.tv:443"

bot:
  nickname: "%env(TWITCHBOT_BOT_NICKNAME)%"
  token: "%env(TWITCHBOT_BOT_TOKEN)%"
  channels:
    - martinph01
    - choccyb0t

broadcaster:
  token: "%env(TWITCHBOT_BROADCASTER_TOKEN)%"


modules:
  # - Choccybiccy\TwitchBot\Modules\QueueModule

events:
  listeners:
    '*':
      - Choccybiccy\TwitchBot\EventListener\DebugListener
    # Choccybiccy\TwitchBot\Event\MessageEvent
    #   - My\TwitchBot\Event\Listener
